### ISSUE TITLE
Example doesn't work anymore

### ISSUE THREAD

**Issue by mexindian** [sipemu/d3Dashboard#2]
Just tried installing your example and all packages today, launches a blank page in Chrome. The console shows some issues:
![image](https://cloud.githubusercontent.com/assets/8094091/11592561/2763726c-9a97-11e5-8882-626c6586e299.png)

What info can I give you to help?

**Comment by sipemu** [comment]
issue is resolved

**Comment by sipemu** [comment]
fixed
